### delete one recipe

DELETE http://localhost:8080/recipeStorage/recipes/2
Accept: application/json

### delete all recipes of an user

DELETE http://localhost:8080/recipeStorage/recipes/user/3

### delete all recipes

DELETE http://localhost:8080/recipeStorage/recipes
Accept: application/json

