### delete ingredient with id
DELETE http://localhost:8080/recipeStorage/steps/1
Accept: application/json

### DELETE ingredients of a recipe

DELETE http://localhost:8080/recipeStorage/recipes/1/steps
Accept: application/json

### delete all ingredients

DELETE http://localhost:8080/recipeStorage/steps
Accept: application/json