PUT http://localhost:8080/recipeStorage/ingredients/1
Accept: application/json
Content-Type: application/json

{
  "name": "Nuovo nome al primo ingrediente"
}

### bad put requests (name is empty)
PUT http://localhost:8080/recipeStorage/ingredients/1
Accept: application/json
Content-Type: application/json

{
  "name": ""
}