GET http://localhost:8080/recipeStorage/users
Accept: application/json

### get by id

GET http://localhost:8080/recipeStorage/users/1
Accept: application/json

### get by nickname
GET http://localhost:8080/recipeStorage/users/nickname/johnd
Accept: application/json