POST http://localhost:8080/recipeStorage/users
Accept: application/json
Content-Type: application/json

[
  {
    "name": "Lucia",
    "surname": "Bianchi",
    "nickname": "dream19",
    "email": "dreamy@gmail.com",
    "dateOfBirth": "2000-12-17",
    "hashPsw": "verysecurepassword"
  },
  {
    "name": "Maria",
    "surname": "Rossi",
    "nickname": "mary",
    "email": "mary@fsks.com",
    "dateOfBirth": "1990-01-01",
    "hashPsw": "12345"
  },
  {
    "name": "Lillo",
    "surname": "Risi",
    "nickname": "lillo",
    "email": "lillo@llill.com",
    "dateOfBirth": "1998-11-21",
    "hashPsw": "lillo1234"
  }
]

### good request
POST http://localhost:8080/recipeStorage/users
Accept: application/json
Content-Type: application/json

[{
  "name": "Anna",
  "surname": "Binny",
  "nickname": "Anyany1",
  "email": "any1@ksksl.com",
  "dateOfBirth": "2010-12-18",
  "hashPsw": "any12345"
}]

### bad request (email not formatted)
POST http://localhost:8080/recipeStorage/users
Accept: application/json
Content-Type: application/json

[{
  "name": "Andrea",
  "surname": "Cirroi",
  "nickname": "Anderrr",
  "email": "notagoodemail",
  "dateOfBirth": "2000-12-17",
  "hashPsw": "andee1000"
}]

### bad request (missing name)
POST http://localhost:8080/recipeStorage/users
Accept: application/json
Content-Type: application/json

[{
  "surname": "Bianchi",
  "nickname": "2dcb11vnioo00iko9",
  "email": "l211uccoghjsemkl00ojjnbknln@gmail.com",
  "dateOfBirth": "2000-12-17",
  "hashPsw": "verysecurepassword"
}]

### bad request (nickname already present)
POST http://localhost:8080/recipeStorage/users
Accept: application/json
Content-Type: application/json

[{
  "name": "Lucia",
  "surname": "Bianchi",
  "nickname": "dream19",
  "email": "l211uccoghjs9emkl00ojjnbknln@gmail.com",
  "dateOfBirth": "2000-12-17",
  "hashPsw": "verysecurepassword"
}]
