### good put request

PUT http://localhost:8080/recipeStorage/users/1
Accept: application/json
Content-Type: application/json

{
  "name": "Gionny",
  "email": "johnnewemail11@1gmail.com",
  "dateOfBirth": "1990-01-01",
  "hashPsw": "12345"
}

### bad put request
PUT http://localhost:8080/recipeStorage/users/1
Accept: application/json
Content-Type: application/json

{
  "name": "Gionny",
  "email": "notanemail"
}
