PUT http://localhost:8080/recipeStorage/users/27
Accept: application/json
Content-Type: application/json

{
  "name": "Maria",
  "email": "johnnewemail11@1gmail.com",
  "dateOfBirth": "1990-01-01",
  "hashPsw": "12345"
}

###